spring.datasource.url=jdbc:postgresql://localhost:5434/auth_db
spring.datasource.username=dev
spring.datasource.password=dev

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=8080

spring.flyway.locations=classpath:com/example/auth/db/migration

# internal HttpClient configuration
internal.http.connect-timeout=3s
internal.http.read-timeout=5s
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG