spring.datasource.url=jdbc:postgresql://localhost:5434/order_db
spring.datasource.username=dev
spring.datasource.password=dev

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=8081

spring.flyway.enabled=true
spring.flyway.locations=classpath:com/example/order/db/migration


# internal HttpClient configuration
internal.http.connect-timeout=3s
internal.http.read-timeout=5s
logging.level.org.flywaydb=DEBUG

# Kafka configuration
kafka.topic.order-created=order-created
spring.kafka.consumer.group-id=order-group

# Common Kafka configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true

# Spring Cloud Stream configuration
spring.cloud.stream.default.contentType=application/json
spring.cloud.stream.bindings.orderCreated-out-0.destination=order-created
spring.cloud.stream.bindings.orderCreated-out-0.contentType=application/json
spring.cloud.stream.kafka.bindings.orderCreated-out-0.producer.configuration.spring.json.type.mapping=orderCreated:com.example.order.event.dto.order.OrderCreatedEventRequest
spring.cloud.stream.kafka.binder.brokers=localhost:9092