spring.datasource.url=jdbc:postgresql://localhost:5434/order_db
spring.datasource.username=dev
spring.datasource.password=dev
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
server.port=8081

spring.flyway.enabled=true
spring.flyway.locations=classpath:com/example/order/db/migration

# Internal HttpClient
internal.http.connect-timeout=3s
internal.http.read-timeout=5s

logging.level.org.flywaydb=DEBUG

# Kafka Binder
spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.kafka.binder.auto-create-topics=true

# Default content type
spring.cloud.stream.default.contentType=application/json

# Binding: output channel
spring.cloud.stream.bindings.orderCreated-out-0.destination=order-created
spring.cloud.stream.bindings.orderCreated-out-0.contentType=application/json

# JSON Serializer config
spring.cloud.stream.kafka.bindings.orderCreated-out-0.producer.configuration.value.serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.cloud.stream.kafka.bindings.orderCreated-out-0.producer.configuration.spring.json.type.mapping=orderCreated:com.example.order.event.dto.order.OrderCreatedEventRequest
spring.cloud.stream.kafka.bindings.orderCreated-out-0.producer.configuration.spring.json.add.type.headers=false