spring.datasource.url=jdbc:postgresql://localhost:5434/payment_db
spring.datasource.username=dev
spring.datasource.password=dev
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082

spring.flyway.enabled=true
spring.flyway.locations=classpath:com/example/payment/db/migration

# Kafka Binder
spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.kafka.binder.auto-create-topics=true

# Default content type
spring.cloud.stream.default.contentType=application/json

# Function binding — tên phải khớp với @Bean method name trong code Java
spring.cloud.function.definition=orderCreated

# Binding: input channel
spring.cloud.stream.bindings.orderCreated-in-0.destination=order-created
spring.cloud.stream.bindings.orderCreated-in-0.group=payment-service-group
spring.cloud.stream.bindings.orderCreated-in-0.contentType=application/json

# Consumer config
spring.cloud.stream.bindings.orderCreated-in-0.consumer.concurrency=3

# Kafka-level consumer config
spring.cloud.stream.kafka.bindings.orderCreated-in-0.consumer.configuration.auto.offset.reset=earliest
spring.cloud.stream.kafka.bindings.orderCreated-in-0.consumer.configuration.default.api.timeout.ms=30000
spring.cloud.stream.kafka.bindings.orderCreated-in-0.consumer.configuration.session.timeout.ms=30000
spring.cloud.stream.kafka.bindings.orderCreated-in-0.consumer.configuration.request.timeout.ms=20000

# JSON Deserializer config
spring.cloud.stream.kafka.bindings.orderCreated-in-0.consumer.configuration.value.deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.cloud.stream.kafka.bindings.orderCreated-in-0.consumer.configuration.spring.json.trusted.packages=com.example.*
spring.cloud.stream.kafka.bindings.orderCreated-in-0.consumer.configuration.spring.json.value.default.type=com.example.payment.event.dto.OrderCreatedEventRequest
spring.cloud.stream.kafka.bindings.orderCreated-in-0.consumer.configuration.spring.json.use.type.headers=false

# Logging
logging.level.org.springframework.cloud.stream=DEBUG
logging.level.org.springframework.integration=DEBUG