spring.datasource.url=jdbc:postgresql://localhost:5434/payment_db
spring.datasource.username=dev
spring.datasource.password=dev

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082

spring.flyway.enabled=true
spring.flyway.locations=classpath:com/example/payment/db/migration

# Kafka Cloud Stream
spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.default.contentType=application/json

# Consumer binding - KHÔNG có comment inline!
spring.cloud.function.definition=orderCreated
spring.cloud.stream.bindings.orderCreated-in-0.destination=orderCreated
spring.cloud.stream.bindings.orderCreated-in-0.group=payment-service-group
spring.cloud.stream.bindings.orderCreated-in-0.contentType=application/json

# FIX OFFSET + JSON deserializer
spring.cloud.stream.bindings.orderCreated-in-0.consumer.auto-offset-reset=earliest
spring.cloud.stream.bindings.orderCreated-in-0.consumer.start-offset=earliest
spring.cloud.stream.bindings.orderCreated-in-0.consumer.concurrency=3

# JSON trusted packages
spring.cloud.stream.bindings.orderCreated-in-0.consumer.configuration.spring.json.trusted.packages=com.example.*